[SETTINGS]
ALARM=1      ;|cameras detect the player | 1 - on | 0 - off
TIME=70      ;|after what time does the camera detect the player
SOUND=2      ;|alarm sound |0 - нет | 1 - short sound | 2 - long sound
OFF=1        ;|the ability to disable cameras using the control panel| 1 - on | 0 - off
REDLIGHT=1   ;|red light when player is detected | 1 - on| 0 - off

# Objects (add using DYOM#):
# Camera - ID 1886
# Control panel - ID 2606
